apiVersion: v1
kind: Service
metadata:
  name: my-node-port
spec:
  type: NodePort
  selector:
    app: ls-lab-4
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 8080

