apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.label.app }}-sample-deployment
  labels:
    app: {{.Values.label.app }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{.Values.label.app }}
  template:
    metadata:
      labels:
        app: {{.Values.label.app }}
    spec:
      containers:
        - name: {{.Values.label.app }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: 8080
          env:
            - name: DEFAULT_TZ
              valueFrom:
                configMapKeyRef:
                  name: {{.Values.label.app }}-config-map
                  key: DEFAULT_TZ
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{.Values.label.app }}-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{.Values.label.app }}-secret
                  key: DB_PASS

