apiVersion: v1
kind: Service
metadata:
  name: my-node-port
spec:
  type: NodePort
  selector:
    app: {{.Values.label.app }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080

