apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.label.app }}-secret
type: Opaque
data:
  DB_USER: {{ .Values.variables.secrets.DB_USER | b64enc }}
  DB_PASS: {{ .Values.variables.secrets.DB_PASS | b64enc }}
